#!/usr/bin/env sh

# "THE BEER-WARE LICENSE" (Revision 42):
# <ctxnop@gmail.com> wrote this file. As long as you retain this notice you
# can do whatever you want with this stuff. If we meet some day, and you think
# this stuff is worth it, you can buy me a beer in return. ctxnop

# If 'vim' is available, set it as default editor
if [ -e "/usr/bin/vim" ]; then
    export EDITOR="/usr/bin/vim"
fi

# If 'less' is available, set it as default pager
if [ -e "/usr/bin/less" ]; then
    export PAGER="/usr/bin/less"
fi

# Set history settings
export HISTFILE="${NOP_HOME}/.histfile"
export HISTSIZE=10000
export SAVEHIST=1000

# If the current user is a standard user
if [ "$(id -u)" -ge "1000" ]; then
    # Add the $NOP_SHARE/bin folder to the path.
    if [ -d "${NOP_SHARE}/bin" ] &&
       [ "$( echo "${PATH}" | grep -oc "${NOP_SHARE}/bin" )" -eq "0" ]; then
        export PATH="${NOP_SHARE}/bin:${PATH}"
    fi

    # Add the $NOP_HOME/bin folder to the path.
    if [ -d "${NOP_HOME}/bin" ] &&
       [ "$( echo "${PATH}" | grep -oc "${NOP_HOME}/bin" )" -eq "0" ]; then
        export PATH="${NOP_HOME}/bin:${PATH}"
    fi
fi
